name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      id: go

    - run: go install golang.org/x/tools/cmd/goimports@latest
    - run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get Modules
      run: make getmodules

    - name: Build Static
      run: make static

    - name: Test
      run: make test
    
    - name: Build All
      run: make build
    
    - name: Upload Linux
      uses: actions/upload-artifact@v2
      with:
        name: bin-linux
        path: bin/tent-linux*

    - name: Upload Darwin
      uses: actions/upload-artifact@v2
      with:
        name: bin-darwin
        path: bin/tent-darwin*

    - name: Upload Windows
      uses: actions/upload-artifact@v2
      with:
        name: bin-windows
        path: bin/tent-windows*
